### ISSUE TITLE
Error: No INFRACOST_API_KEY environment variable is set.

### ISSUE THREAD

**Issue by heathsnow** [infracost/actions#173]
## Description

I've started getting this error when running the action:

> Error: No INFRACOST_API_KEY environment variable is set.

My workflows worked fine last time they ran so I'm wondering if something has changed with `v2` since then.

From my understanding I only need the setup action to reference the API secret, like so:

```yaml
    steps:
      - name: 'Setup Infracost'
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
```

However, once I get to follow-up steps to either `breakdown` or `diff` I get the error.

Any idea what's going on?

Thanks in advance.

**Comment by tim775** [comment]
Hi, there haven't been any changes to the action, but we did just release a new CLI version that would have been picked up by a new run.

When did the error happen and when was that last time it ran succesfully?

It also might not be a bad idea to "try again" since github had [a pretty serious outage](https://www.githubstatus.com/incidents/f0mhbz9xn497) earlier today.

**Comment by heathsnow** [comment]
Yep, I'm able to get it passing again if I use this:

```yaml
    steps:
      - name: 'Setup Infracost'
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          version: 0.10.20
```

So something is wrong with the latest `0.10.21` version.
