### ISSUE TITLE
feature: support multi api-key

### ISSUE THREAD

**Issue by rfyiamcool** [infracost/actions#178]
### summary

infracost/actions support multiple api-key  ? 

```yaml
on: [pull_request]
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  infracost:
    name: Infracost
    runs-on: ubuntu-latest
    permissions:
      contents: read
      # Required to post comments
      pull-requests: write
  
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}  // 😁 
```
