### ISSUE TITLE
Action not working with Terraform Cloud

### ISSUE THREAD

**Issue by alex-feel** [infracost/actions#52]
First I used [this guide](https://github.com/infracost/actions/tree/master/examples/terraform-cloud-enterprise). After I got the error:

```
Error: terraform plan failed: exit status 1

Try setting the --path to a Terraform plan JSON file. See https://infracost.io/troubleshoot for how to generate this.
Error: Process completed with exit code 1.
```

I have tried several other options, all without success.

My last GitHub Actions configuration looks like this:

```yml
name: Terraform

on:
  push:
    branches:
      - main
    paths:
      - '**.tf'
  pull_request:
    paths:
      - '**.tf'

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: 1.1.5

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -recursive
        working-directory: ${{ env.working-directory }}

      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ${{ env.working-directory }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.working-directory }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run TFLint
        run: tflint --format compact
        working-directory: ${{ env.working-directory }}

      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color -compact-warnings
        working-directory: ${{ env.working-directory }}
        continue-on-error: true

      - name: Truncate Terraform Plan
        if: github.event_name == 'pull_request'
        run: |
          plan=$(cat <<'EOF'
          ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
          EOF
          )
          echo "PLAN<<EOF" >> $GITHUB_ENV
          echo "${plan:0:65536}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update Pull Request
        uses: actions/github-script@v5
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `
            **Terraform Format and Style**: \`${{ steps.fmt.outcome }}\`
            **Terraform Initialization**: \`${{ steps.init.outcome }}\`
            **Terraform Plan**: \`${{ steps.plan.outcome }}\`
            **Terraform Validation**: \`${{ steps.validate.outcome }}\`

            <details><summary>Plan Details</summary>

            \`\`\`terraform
            ${process.env.PLAN}
            \`\`\`\

            </details>

            **Pusher**: @${{ github.actor }}
            **Action**: \`${{ github.event_name }}\`
            `
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Setup Infracost
        if: github.event_name == 'pull_request'
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Infracost JSON
        if: github.event_name == 'pull_request'
        run: infracost breakdown --path ${{ env.working-directory }} --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}

      - name: Post Infracost Comment
        if: github.event_name == 'pull_request'
        uses: infracost/actions/comment@v1
        with:
          path: /tmp/infracost.json
          behavior: new

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: ${{ env.working-directory }}

```

All `*.tf` files are located **in the root of the repository**.

Each run of `Generate Infracost JSON` step looks like this:

```hcl
Run infracost breakdown --path . --format json --out-file /tmp/infracost.json
  infracost breakdown --path . --format json --out-file /tmp/infracost.json
  shell: /usr/bin/bash -e {0}
  env:
    working-directory: .
    TERRAFORM_CLI_PATH: /home/runner/work/_temp/f790a945-b2d2-4cfb-b698-7f567a359822
    PLAN: Running plan in the remote backend. Output will stream here. Pressing Ctrl-C
  will stop streaming the logs, but will not stop the plan running remotely.
  
  Preparing the remote plan...
  
  To view this run in a browser, visit:
  https://app.terraform.io/app/website/test/runs/run-9d2nNaVjbf4sPWG5
  
  Waiting for the plan to start...
  
  Terraform v1.1.5
  on linux_amd64
  Configuring remote state backend...
  Initializing Terraform configuration...


(removed for brevity)

  
  Plan: 4 to add, 0 to change, 0 to destroy.
  ╷
  │ Warning: Experimental feature "module_variable_optional_attrs" is active
  │ 
  │   on .terraform/modules/acme_com/main.tf line 2, in terraform:
  │    2:   experiments = [module_variable_optional_attrs]
  │ 
  │ Experimental features are subject to breaking changes in future minor or
  │ patch releases, based on feedback.
  │ 
  │ If you have feedback on the design of this feature, please open a GitHub
  │ issue to discuss it.
  ╵
    INFRACOST_GITHUB_ACTION: true
    INFRACOST_SKIP_UPDATE_CHECK: true
    INFRACOST_VCS_REPOSITORY_URL: https://github.com/website/terraform-test
    INFRACOST_VCS_PULL_REQUEST_URL: https://github.com/website/terraform-test/pull/13
    INFRACOST_LOG_LEVEL: info
time="2022-02-22T18:00:31Z" level=info msg="Detected Terraform directory at ."
time="2022-02-22T18:00:31Z" level=info msg="Starting: Running terraform plan"

Error: terraform plan failed: exit status 1

Try setting the --path to a Terraform plan JSON file. See https://infracost.io/troubleshoot for how to generate this.
Error: Process completed with exit code 1.
```

I have several questions:

1. [It says](https://www.infracost.io/docs/features/cli_commands/#option-1-terraform-directory) that you can point to the Terraform configuration directory, how do you specify that the directory is the top level directory in the repository? I've tried different options - none work.
2. How exactly to specify parameters when using Action? [Here](https://github.com/infracost/actions/tree/master/examples/terraform-cloud-enterprise) `=` sign is used between the parameter and its value like this: `infracost breakdown --path=examples/terraform-cloud-enterprise/code --format=json --out-file=/tmp/infracost.json`, and on the [main page](https://github.com/marketplace/actions/infracost-actions) the parameter and its value are separated by a space like this: `infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json`. Are both options acceptable or is the documentation out of date?
3. How to make it work with Terraform Cloud?
