### ISSUE TITLE
Empty Infracost output

### ISSUE THREAD

**Issue by dcarbone** [infracost/actions#71]
I'm attempting to use v2 of the infracost action from a `plan` output json and running into a bizarre issue.  The step runs successfully, is able to identify input and output files, but the comment step always produces an empty comment:

<img width="631" alt="Screen Shot 2022-06-22 at 1 48 50 PM" src="https://user-images.githubusercontent.com/1392439/175114117-7c003e56-c8ed-4f26-ae88-456564dcdade.png">

The step code looks something like this:

```yaml
steps:
  - name: Generate Infracost diff
    id: infracost-diff
    run: |
      # define vars
      _infile="${{ steps.terraform-show.outputs.outfile }}"
      _outfile="/tmp/infracost.json"
      
      # execute infracost
      infracost diff \
        --path="${_infile}" \
        --format=json \
        --out-file="${_outfile}"
      
      # set outputs
      echo "::set-output name=outfile::${_outfile}"
```

Any pointers?  The entirely empty output is puzzling!
